version: '3.1'
services:

    postgis:
        image: postgis/postgis
        container_name: postgis
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: user
        volumes:
            - ./data:/var/lib/postgresql/data
            - ./postgis-workshop:/postgis-workshop

    pgadmin4:
        image: dpage/pgadmin4
        container_name: pgadmin4
        ports:
            - '5050:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        volumes:
            - ./postgis-workshop:/pgadmin4/postgis-workshop
        links:
            - postgis

volumes:
  postgis-data: